[project]
name = "amuse-ph4"
version = "2024.04.0"
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["ph4/**/*.py"]
exclude = ["ph4/amuse-ph4*"]
artifacts = ["ph4/cpu_worker"]

[tool.hatch.build.targets.wheel.sources]
"ph4" = "amuse/community/ph4"

