[project]
name = "amuse-ph4-cpu"
version = "2024.04.0"
dependencies = [
    "amuse-framework"
]

[tool.setuptools.package-dir]
"amuse.community.ph4" = "."

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

